- hosts: trainserver
  gather_facts: no

  tasks:
    - name: install package 
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - git
        - nodejs
      become: yes
      

      
