- hosts: trainserver

  tasks:
    - name: remove git
      ansible.builtin.apt:
        name: git
        state: absent
      become: yes
      tags: git
    
    - name: remove nodejs
      ansible.builtin.apt:
        name: nodejs
        state: absent
      become: yes
      tags: nodejs