- hosts: trainserver
  remote_user: ubuntu
  vars:
    nginx_port: 80
    root_dir: ../files
    nginx: /etc/nginx

  tasks: 
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      become: yes

    - name: update kozlovjr config
      ansible.builtin.template:
        src: "{{root_dir}}/kozlovjr.conf"
        dest: "{{nginx}}/sites-available/kozlovjr.conf"
      notify:
        - restart nginx
      become: yes

    - name: create symbolik link
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/kozlovjr.conf"
        dest: "/etc/nginx/sites-enabled/kozlovjr.conf"
        state: link 
      notify:
        - restart nginx
      become: yes

  handlers: 
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes