- hosts: trainserver
  vars:
    users:
      - {name: "jaime", email: jaime@test.com }
      - {name: "sansa", email: sansa@test.com}
      - {name: "robert", email: robert@test.com}
    pub_key: ../files/ssh-key_pub.txt

  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{ user.name }}"
        state: present
      loop:
        - "{{ users }}"
    
    - name: add gitconfig file
      ansible.builtin.template:
        src: "../files/gitconfig"
        dest: "/home{{user.name}}/.gitconfig"
      loop:
        - "{{ users }}"
     
    - name: add